http:
  port: 39190
  adminPort: 39191
  gzip:
    enabled: false

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: TRACE

  # Logger-specific levels.
  loggers:
    "javax.management.mbeanserver": WARN
    "org.eclipse.jetty": WARN
    "com.sun.jersey": WARN
    "java.awt": WARN
    "sun.awt": WARN
    "Kompics": WARN
    "se.sics.kompics": WARN
    "se.sics.kompics.network": WARN
    
    "se.sics.ktoolbox": INFO
     
    "se.sics.gvod": INFO
    "se.sics.ms": INFO
    "se.sics.ws": INFO
    
  console:
      enabled: true

  file:
      enabled: true
      currentLogFilename: "mylog.log"
      archivedLogFilenamePattern: "mylog-%d{yyyy-mm-dd}.log.gz"