http:
  port: 29190
  adminPort: 29191
  gzip:
    enabled: false

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    "Kompics": INFO
    "se.sics.kompics.timer.java.JavaTimer": INFO
    "se.sics.ktoolbox.cc.bootstrap.CCBootstrapComp": INFO
    "se.sics.ktoolbox.cc.heartbeat.CCHeartbeatComp": INFO
    "se.sics.ktoolbox.cc.common.config.CaracalClientConfig": INFO
    "se.sics.ktoolbox.croupier.CroupierComp" : WARN
    "se.sics.gvod.system.HostManagerComp": INFO
    "se.sics.gvod.core.VoDComp": INFO
    "se.sics.gvod.core.connMngr.ConnMngrComp": INFO
    "se.sics.gvod.core.downloadMngr.DownloadMngrComp": INFO
    "se.sics.gvod.manager.VoDManager": INFO
    "se.sics.ktoolbox.election.core.ElectionLeader": DEBUG
    
  console:
      enabled: true

  file:
      enabled: true
      currentLogFilename: "mylog.log"
      archivedLogFilenamePattern: "mylog-%d{yyyy-mm-dd}.log.gz"